# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.2.9

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git
# Install PHP extensions
- docker-php-ext-install mbstring pdo_pgsql curl json intl gd xml zip bz2 opcache
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
- mkdir -p ~/.ssh
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
- mysql:5.7

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: mysql_database
  MYSQL_ROOT_PASSWORD: mysql_strong_password
stages:
- deploy

deploy:
  stage: deploy
  only:
  - master
  script:
  - echo "Deployment loading"
  - scp -r ./* $server_user@$server_host:/var/www/vhosts/louisthomas.fr/handball.louisthomas.fr/
  - ssh $server_user@$server_host "cd /var/www/vhosts/louisthomas.fr/handball.louisthomas.fr/ && composer install --no-dev --optimize-autoloader"
  - ssh $server_user@$server_host "rm -rf /var/www/vhosts/louisthomas.fr/handball.louisthomas.fr/var/cache && rm -rf /var/www/vhosts/louisthomas.fr/handball.louisthomas.fr/var/log"
  - ssh $server_user@$server_host "chmod -R 777 /var/www/vhosts/louisthomas.fr/handball.louisthomas.fr/var"
  - echo "var and log folders deleted and access rights applicated"
